apiVersion: v1
kind: PersistentVolume
metadata:
  name: liferay-pv-postgres1
  labels:
    app: liferay-pv-postgres
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"