apiVersion: v1
kind: Namespace
metadata:
  name: liferay-client10-build
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build
  namespace: liferay-client10-build
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildx
  namespace: liferay-client10-build
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: build
  namespace: liferay-client10-build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: build
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: buildx-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: buildx
  namespace: liferay-client10-build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
