apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "liferay.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{  .Values.clientname }}
{{ include "liferay.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "liferay.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: {{  .Values.clientname }}
  strategy:
     type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "liferay.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{  .Values.clientname }}
    spec:
        containers:
        - env:
          - name: DB_TYPE
            value: POSTGRESQL
          - name: DB_ENDPOINT
            value: jdbc:postgresql://postgres.liferay:5432/{{ .Values.clientname  }}
          - name: DB_USER
            value: admin
          - name: DB_PASS
            value: 1q2q2w3w
          name: {{ .Values.clientname  }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/bin/bash", "-ce", "/opt/liferay-portal-6.2-ce-ga6/tomcat-7.0.62/bin/catalina.sh run" ]
          ports:
          - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /opt/liferay-portal/data
            name: liferay-data
          - mountPath: /opt/liferay-portal/deploy
            name: liferay-deploy
          - mountPath: /opt/liferay-portal/tomcat-7.0.62/logs
            name: liferay-logs
        restartPolicy: Always            
        volumes:
        - name: liferay-data
          persistentVolumeClaim:
            claimName: {{ .Values.clientname  }}-data-claim
        - name: liferay-deploy
          persistentVolumeClaim:
            claimName: {{ .Values.clientname  }}-deploy-claim
        - name: liferay-logs
          persistentVolumeClaim:
            claimName: {{ .Values.clientname  }}-logs-claim     
        {{- with .Values.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.affinity }}
        affinity:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.tolerations }}
        tolerations:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.imagePullSecrets }}
        imagePullSecrets:
         {{- toYaml . | nindent 8 }}
       {{- end }}