apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{  .Values.clientname }}-data
  labels:
    app: {{  .Values.clientname }}
    type: local
    assign-to: {{  .Values.clientname }}-data
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/naseej_volumes/medad/{{  .Values.clientname }}/liferaydata"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{  .Values.clientname }}-deploy
  labels:
    app: {{  .Values.clientname }}
    type: local
    assign-to: {{  .Values.clientname }}-deploy
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/naseej_volumes/medad/{{  .Values.clientname }}/deploy"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{  .Values.clientname }}-logs
  labels:
    app: {{  .Values.clientname }}
    type: local
    assign-to: {{  .Values.clientname }}-logs
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/naseej_volumes/medad/{{  .Values.clientname }}/logs"   