apiVersion: v1
<<<<<<< HEAD

kind: Namespace

metadata:

  name: liferay-client10-build



---



apiVersion: v1

kind: ServiceAccount

metadata:

  name: build

  namespace: liferay-client10-build



---



apiVersion: rbac.authorization.k8s.io/v1beta1

kind: RoleBinding

metadata:

  name: build

  namespace: liferay-client10-build

roleRef:

  apiGroup: rbac.authorization.k8s.io

  kind: ClusterRole

  name: admin

subjects:

- kind: ServiceAccount

  name: build



---



apiVersion: v1

kind: LimitRange

metadata:

  name: build

  namespace: liferay-client10-build

spec:

  limits:

  - default:

      memory: 200Mi

      cpu: 0.2

    defaultRequest:

      memory: 100Mi

      cpu: 0.1

    max:

      memory: 500Mi

      cpu: 0.5

    min:

      memory: 10Mi

      cpu: 0.05

    type: Container



---



apiVersion: v1

kind: ResourceQuota

metadata:

  name: build

  namespace: liferay-client10-build

spec:

  hard:

    requests.cpu: 2

    requests.memory: 3Gi

    limits.cpu: 3

    limits.memory: 4Gi

    pods: 15
=======
kind: Namespace
metadata:
  name: liferay-client10-build
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build
  namespace: liferay-client10-build
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildx
  namespace: liferay-client10-build
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: build
  namespace: liferay-client10-build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: build
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: buildx-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: buildx
  namespace: liferay-client10-build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
>>>>>>> client_10
