#Persistent Volume Claim for Deploy Folder
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liferay-client10-deploy-claim
  namespace: liferay
  labels:
    app: liferay_client10
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      assign-to: liferay-client10-deploy
---
#Persistent Volume Claim for data folder
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liferay-client10-data-claim
  namespace: liferay
  labels:
    app: liferay_client10
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      assign-to: liferay-client10-data
---
#Persistent Volume Claim for log folder
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liferay-client10-logs-claim
  namespace: liferay
  labels:
    app: liferay_client10
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      assign-to: liferay-client10-logs