# Default values for liferay.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 558184000342.dkr.ecr.us-west-2.amazonaws.com/naseejmedad
  tag: client10
  pullPolicy: Always


clientname: liferayclient10
imagePullSecrets:
  - name:  aws-registry
nameOverride: ""
fullnameOverride: ""

service:
  port: 8080
  type: ClusterIP

ingress:
  enabled: true
  annotations:
     kubernetes.io/ingress.class: nginx
     ingress.kubernetes.io/ssl-redirect: "false"
     nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: 35.166.225.194.nip.io


  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
     memory: 3Gi
  requests:
     memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
